### ISSUE TITLE
Responsive should allow different selector

### ISSUE THREAD

**Issue by Deklin** [ahmed-wagdi/angular-joyride#16]
We have a situation where when in large screen mode an element is on the screen, however once the screen collapses down, it changes to a button with a different locator. Consider adding a different selector to responsive mode.

**Comment by ahmed-wagdi** [comment]
I would rather not overcomplicate the directive by trying to handle every single case. This problem can be resolved easily by adding a `resize` event handler on the window and just change the steps array as you like at certain breakpoints.

You should be able to handle all responsive issues this way, the only reason i added a responsive placement feature was because it's a very common problem so i thought i'd just make it easier but even that could be resolved by utilizing the resize event.
