### ISSUE TITLE
Links on joyride step

### ISSUE THREAD

**Issue by orlandovallejos** [ahmed-wagdi/angular-joyride#9]
I need to let the user click on a link and open a new tab for documentation, for example.
Can't we allow the cases where the click opens a new tab with target="_blank" or some customizable click?

I know that this cancel the click event:

/// When joyride is nested inside an element this 
/// prevents any functions or state changes that are 
/// binded to the parentfrom executing when 
/// clicking on the joyride

angular.element(joyrideContainer).on('click', function(event) {
  event.preventDefault();
  event.stopPropagation();
});

**Comment by ahmed-wagdi** [comment]
That shouldn't be a problem to add, i could make the event-blocking functionality optional on each step then you can handle it in a click function or something similar.

I'll get around to it as soon as i can.

**Comment by ahmed-wagdi** [comment]
@orlandovallejos i changed the event blocking so that it only happens on steps of **type "element"** AND **appendToBody isnt set to true**. If you're step is set to "element" and you're still having this problem then try setting appendToBody to true.

Try this after updating the joyride and let me know how it goes.
